Unit testing
AlenaTMW/testRepo pull request #5
Opened 2021-07-25 22:43 UTC by AlenaTMW

Please, check my homework.

2021-07-26 06:20 UTC, rat6666 requested changes

2021-07-26 06:20 UTC, rat6666 commented on lesson_05/shapedescription/shapedescription.go
> +	}
It can be done in one condition r.Height <=0 || ....

2021-07-26 06:20 UTC, rat6666 commented on lesson_05/shapedescription/shapedescription.go
> +	fmt.Printf("Area: %.2f\n", a)
Why did you skip handling the error? You should ckeck if err != nil {} else {}

2021-07-27 07:50 UTC, dimonl approved these changes

2021-07-27 11:54 UTC, rat6666 approved these changes

2021-07-27 13:38 UTC, merged